name: qr_app
description: "Secure QR code scanner app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auth_biometric:
    path: packages/auth_biometric
  qr_scanner:
    path: packages/qr_scanner
  cupertino_icons: 1.0.8
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_secure_storage: 9.2.4

  shared_preferences: 2.5.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  url_launcher: 6.3.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  melos: 6.3.2
  mockito: 5.4.4
  build_runner: 2.4.6
  pigeon: 21.1.0
  hive_generator: 2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
