name: qr_scanner
description: "A new Flutter package project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  equatable: 2.0.7
  flutter:
    sdk: flutter
  pigeon: 21.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: dev.flutter.qr_scanner
        pluginClass: NativeMobileQr