name: auth_biometric
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pigeon: 21.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: dev.flutter.auth_biometric
        pluginClass: NativeMobileAuthBiometric
